version: 0.1
   
phases:
  install:
    commands:
      - gem install bundler 
      - bundle install
      - gem install jekyll
  build:
    commands:
      - echo "******** Building Jekyll site ********"
      - jekyll build
      - echo "******** Uploading to S3 ********"
      - aws s3 sync _site/ s3://samdeepnayak.com

